version: '3'
services:

  rails:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@database:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    depends_on:
      - database
    command:
      ["bash", "-c", "rm -f tmp/pids/server.pid; rails server -b 0.0.0.0"]

  database:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
