version: "2"

services:
  rails:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: "rm -f /app/tmp/pids/server.pids && rails s -p 3000 -b 0.0.0.0"
    env_file:
      - "./.env"
    volumes:
      - ".:/app"
      - cache:/cache
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: always
  db:
    image: mysql:5.7.10
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes_from:
      - data
    restart: always
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/mysql"
      - "bundle:/usr/local/bundle"
    restart: always
volumes:
  db:
    driver: local
  bundle:
    driver: local
  cache:
    driver: local
